config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  resources :categories, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true


end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end
  def new
    @category = Category.new
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category deleted successfully'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>

app/views/categories/index.html.erb
<h1>Category</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to :edit, edit_category_path(category) %>
      <%= button_to :delete, category_path(category), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'new', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<% if user_signed_in? %>
  <h2> Hello <%= current_user.email %> </h2>
  <%= link_to 'Sign out', destroy_user_session_path, data: { 'turbo-method': :delete } %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>